root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/metro"
cmd = "go build -o ./tmp/metro"
delay = 0
exclude_dir = ["node_modules", "assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = [
  ".",
  "views",
  "pkg",
  "websites/two-d",
  "websites/virtual-world",
  "websites/city-editor",
]
include_ext = ["go", "html", "css", "js"]
include_file = ["reporter.go", "main.go"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
