// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: edge.sql

package dbstore

import (
	"context"
)

const createEdge = `-- name: CreateEdge :one
INSERT INTO edge (fromId, toId) 
VALUES (?, ?)
RETURNING id
`

type CreateEdgeParams struct {
	Fromid int64
	Toid   int64
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEdge, arg.Fromid, arg.Toid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAllEdgePoints = `-- name: DeleteAllEdgePoints :exec
DELETE FROM edge_point
`

func (q *Queries) DeleteAllEdgePoints(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEdgePoints)
	return err
}

const deleteAllEdges = `-- name: DeleteAllEdges :exec
DELETE FROM edge
`

func (q *Queries) DeleteAllEdges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEdges)
	return err
}

const getEdgePoints = `-- name: GetEdgePoints :many
SELECT id, edgeId, X, Y, Z, odr
FROM edge_point
WHERE edgeId = ?
ORDER BY odr
`

type GetEdgePointsRow struct {
	ID     int64
	Edgeid int64
	X      float64
	Y      float64
	Z      float64
	Odr    int64
}

func (q *Queries) GetEdgePoints(ctx context.Context, edgeid int64) ([]GetEdgePointsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEdgePoints, edgeid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEdgePointsRow
	for rows.Next() {
		var i GetEdgePointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Edgeid,
			&i.X,
			&i.Y,
			&i.Z,
			&i.Odr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdges = `-- name: GetEdges :many
SELECT id, fromId, toId
FROM edge
`

func (q *Queries) GetEdges(ctx context.Context) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(&i.ID, &i.Fromid, &i.Toid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
