// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbstore

import (
	"database/sql"
	"time"
)

type Edge struct {
	ID     int64
	Fromid int64
	Toid   int64
}

type EdgePoint struct {
	ID     int64
	Edgeid int64
	Odr    int64
	X      float64
	Y      float64
	Z      float64
}

type Line struct {
	ID        int64
	Name      string
	Color     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Make struct {
	ID           int64
	Name         string
	Description  string
	Acceleration sql.NullFloat64
	TopSpeed     sql.NullFloat64
	Color        sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Passenger struct {
	ID                   string
	Name                 string
	CurrentStationID     int64
	DestinationStationID int64
	CurrentTrainID       sql.NullInt64
	State                string
	Sentiment            float64
	SpawnTime            time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type PassengerEvent struct {
	ID          int64
	PassengerID string
	EventType   string
	StationID   sql.NullInt64
	TrainID     sql.NullInt64
	Sentiment   sql.NullFloat64
	Metadata    sql.NullString
	CreatedAt   time.Time
}

type Schedule struct {
	ID            int64
	TrainID       int64
	StationID     int64
	ScheduledTime int64
	SequenceOrder int64
	CreatedAt     time.Time
}

type Station struct {
	ID        int64
	Name      string
	X         sql.NullFloat64
	Y         sql.NullFloat64
	Z         sql.NullFloat64
	Color     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StationLine struct {
	ID        int64
	Stationid sql.NullInt64
	Lineid    sql.NullInt64
	Odr       sql.NullInt64
}

type Train struct {
	ID        int64
	Name      string
	X         float64
	Y         float64
	Z         float64
	Currentid sql.NullInt64
	Nextid    sql.NullInt64
	Makeid    sql.NullInt64
	Lineid    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}
