// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbstore

import (
	"database/sql"
	"time"
)

type Line struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Station struct {
	ID        int64
	Name      string
	X         sql.NullFloat64
	Y         sql.NullFloat64
	Z         sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type StationLine struct {
	ID        int64
	Stationid sql.NullInt64
	Lineid    sql.NullInt64
}

type Train struct {
	ID        int64
	Name      string
	X         float64
	Y         float64
	Z         float64
	Currentid sql.NullInt64
	Nextid    sql.NullInt64
	CreatedAt time.Time
	UpdatedAt time.Time
}
