// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package city

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Editor() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>City Editor</title><link rel=\"stylesheet\" href=\"/css/editor.css\"><link rel=\"stylesheet\" href=\"/css/dialog.css\"></head><body><h1>City Editor</h1><canvas id=\"editorCanvas\"></canvas><div id=\"dialog\" class=\"confirm-dialog\"><div class=\"confirm-dialog-body\"><h1 class=\"confirm-dialog-title\">A custom modal popup</h1><p class=\"confirm-dialog-text\"></p><button id=\"yesBtn\" type=\"button\" class=\"confirm-dialog-yes\">yes</button> <button id=\"noBtn\" type=\"button\" class=\"confirm-dialog-no\">no</button></div></div><div id=\"controls\"><button onclick=\"dispose()\">🗑️</button> <button id=\"saveBtn\">💾</button> <label for=\"fileInput\" class=\"file-input-label\">📂 <input type=\"file\" id=\"fileInput\" accept=\".world\" onchange=\"load(event)\"></label> <button onclick=\"openOsmPanel()\">🗺️</button> &nbsp; <button id=\"graphBtn\">️🌐</button> <button id=\"startBtn\" onclick=\"setMode(&#39;start&#39;)\">️🏎️</button><div id=\"osmPanel\" style=\"display:none;\"><textarea id=\"osmDataContainer\" placeholder=\"Paste OSM data here\" rows=\"10\" cols=\"50\"></textarea><div><button onclick=\"loadOsmData()\">✔️</button> <button onclick=\"closeOsmPanel()\">❌</button></div></div></div><script type=\"module\" src=\"/js/primitives/point.js\"></script><script type=\"module\" src=\"/js/primitives/segment.js\"></script><script type=\"module\" src=\"/js/math/graph.js\"></script><script type=\"module\" src=\"/js/math/utils.js\"></script><script type=\"module\" src=\"/js/viewport.js\"></script><script type=\"module\" src=\"/js/world.js\"></script><script type=\"module\" src=\"/js/load.js\"></script><script type=\"module\" src=\"/js/utils/consts.js\"></script><script type=\"module\" src=\"/js/editors/networkEditor.js\"></script><script type=\"module\" src=\"/js/emain.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
