// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package VirtualWorld

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>World Editor</title><link rel=\"stylesheet\" href=\"/vw-css/index.css\"></head><body><h1>World Editor</h1><canvas id=\"theCanvas\"></canvas><div id=\"controls\"><button onclick=\"dispose()\">🗑️</button> <button onclick=\"save()\">💾</button></div><script src=\"/vw-js/primitives/point.js\"></script><script src=\"/vw-js/primitives/segment.js\"></script><script src=\"/vw-js/primitives/envelope.js\"></script><script src=\"/vw-js/primitives/polygon.js\"></script><script src=\"/vw-js/math/graph.js\"></script><script src=\"/vw-js/math/utils.js\"></script><script src=\"/vw-js/viewport.js\"></script><script src=\"/vw-js/graphEditor.js\"></script><script src=\"/vw-js/main.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
