// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package TwoD

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>2D</title><link rel=\"stylesheet\" href=\"/css/index.css\"></head><body><canvas id=\"carCanvas\"></canvas><div id=\"verticalButtons\"><button onclick=\"save()\">💾</button> <button onclick=\"discard()\">🗑️</button></div><canvas id=\"networkCanvas\"></canvas><script src=\"/js/utils.js\"></script><script src=\"/js/visualizer.js\"></script><script src=\"/js/network.js\"></script><script src=\"/js/sensor.js\"></script><script src=\"/js/road.js\"></script><script src=\"/js/controls.js\"></script><script src=\"/js/car.js\"></script><script src=\"/js/main.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
